server:
  port: 8300

micro-system:
  path:
    database: D:/Temp/Temp/20170413
    
spring:
  jpa:
    show-sql: true  
    hibernate:  
      ddl-auto: update
  datasource:
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:${micro-system.path.database}/${spring.application.name};create=true
    username: dbuser
    password: dbpass
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    account-service:
        path: /accounts/**
        serviceId: libra-account-service
        stripPrefix: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8200/eureka/